#include "assets.h"
#include "controllers/contrib/auth_controller.h"
#include "controllers/contrib/gapprole_controller.h"
#include "controllers/contrib/ggroups_controller.h"
#include "controllers/contrib/gusers_controller.h"
#include "controllers/contrib/gusersgroups_controller.h"
#include "controllers/contrib/root_controller.h"
